spring:
  application:
    name: hello-spring-cloud-web-admin-feign-test

server:
  port: 8766

feign:
  hystrix:
    enabled: true  #熔断机制默认关闭

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/